import type { Endpoint } from "./types.js";

const docs = (page: string) => `https://postmarkapp.com/developer/api/${page}`;

export const endpoints: Endpoint[] = [
  {
    name: "email send",
    pattern: ["email", "send"],
    method: "POST",
    path: "/email",
    auth: "server",
    mutation: true,
    description: "Send a single email.",
    docs: docs("email-api"),
  },
  {
    name: "email batch",
    pattern: ["email", "batch"],
    method: "POST",
    path: "/email/batch",
    auth: "server",
    mutation: true,
    description: "Send batch emails.",
    docs: docs("email-api"),
  },
  {
    name: "bulk send",
    pattern: ["bulk", "send"],
    method: "POST",
    path: "/email/bulk",
    auth: "server",
    mutation: true,
    description: "Send bulk emails.",
    docs: docs("bulk-email"),
  },
  {
    name: "bulk get",
    pattern: ["bulk", "get", ":bulkRequestId"],
    method: "GET",
    path: "/email/bulk/:bulkRequestId",
    auth: "server",
    description: "Get the status/details of a bulk API request.",
    docs: docs("bulk-email"),
  },
  {
    name: "bounces delivery-stats",
    pattern: ["bounces", "delivery-stats"],
    method: "GET",
    path: "/deliverystats",
    auth: "server",
    description: "Get delivery stats.",
    docs: docs("bounce-api"),
  },
  {
    name: "bounces list",
    pattern: ["bounces", "list"],
    method: "GET",
    path: "/bounces",
    auth: "server",
    description: "Get bounces.",
    docs: docs("bounce-api"),
  },
  {
    name: "bounces get",
    pattern: ["bounces", "get", ":bounceId"],
    method: "GET",
    path: "/bounces/:bounceId",
    auth: "server",
    description: "Get a single bounce.",
    docs: docs("bounce-api"),
  },
  {
    name: "bounces dump",
    pattern: ["bounces", "dump", ":bounceId"],
    method: "GET",
    path: "/bounces/:bounceId/dump",
    auth: "server",
    description: "Get bounce dump.",
    docs: docs("bounce-api"),
  },
  {
    name: "bounces activate",
    pattern: ["bounces", "activate", ":bounceId"],
    method: "PUT",
    path: "/bounces/:bounceId/activate",
    auth: "server",
    mutation: true,
    description: "Activate a bounce.",
    docs: docs("bounce-api"),
  },
  {
    name: "templates send",
    pattern: ["templates", "send"],
    method: "POST",
    path: "/email/withTemplate",
    auth: "server",
    mutation: true,
    description: "Send email with template.",
    docs: docs("templates-api"),
  },
  {
    name: "templates batch",
    pattern: ["templates", "batch"],
    method: "POST",
    path: "/email/batchWithTemplates",
    auth: "server",
    mutation: true,
    description: "Send batch with templates.",
    docs: docs("templates-api"),
  },
  {
    name: "templates push",
    pattern: ["templates", "push"],
    method: "PUT",
    path: "/templates/push",
    auth: "server",
    mutation: true,
    description: "Push templates to another server.",
    docs: docs("templates-api"),
  },
  {
    name: "templates get",
    pattern: ["templates", "get", ":templateIdOrAlias"],
    method: "GET",
    path: "/templates/:templateIdOrAlias",
    auth: "server",
    description: "Get a template.",
    docs: docs("templates-api"),
  },
  {
    name: "templates create",
    pattern: ["templates", "create"],
    method: "POST",
    path: "/templates",
    auth: "server",
    mutation: true,
    description: "Create a template.",
    docs: docs("templates-api"),
  },
  {
    name: "templates update",
    pattern: ["templates", "update", ":templateIdOrAlias"],
    method: "PUT",
    path: "/templates/:templateIdOrAlias",
    auth: "server",
    mutation: true,
    description: "Edit a template.",
    docs: docs("templates-api"),
  },
  {
    name: "templates list",
    pattern: ["templates", "list"],
    method: "GET",
    path: "/templates",
    auth: "server",
    description: "List templates.",
    docs: docs("templates-api"),
  },
  {
    name: "templates delete",
    pattern: ["templates", "delete", ":templateIdOrAlias"],
    method: "DELETE",
    path: "/templates/:templateIdOrAlias",
    auth: "server",
    mutation: true,
    description: "Delete a template.",
    docs: docs("templates-api"),
  },
  {
    name: "templates validate",
    pattern: ["templates", "validate"],
    method: "POST",
    path: "/templates/validate",
    auth: "server",
    mutation: true,
    description: "Validate a template.",
    docs: docs("templates-api"),
  },
  {
    name: "server get",
    pattern: ["server", "get"],
    method: "GET",
    path: "/server",
    auth: "server",
    description: "Get the current server.",
    docs: docs("server-api"),
  },
  {
    name: "server update",
    pattern: ["server", "update"],
    method: "PUT",
    path: "/server",
    auth: "server",
    mutation: true,
    description: "Edit the current server.",
    docs: docs("server-api"),
  },
  {
    name: "servers list",
    pattern: ["servers", "list"],
    method: "GET",
    path: "/servers",
    auth: "account",
    description: "List servers.",
    docs: docs("servers-api"),
  },
  {
    name: "servers get",
    pattern: ["servers", "get", ":serverId"],
    method: "GET",
    path: "/servers/:serverId",
    auth: "account",
    description: "Get a server.",
    docs: docs("servers-api"),
  },
  {
    name: "servers create",
    pattern: ["servers", "create"],
    method: "POST",
    path: "/servers",
    auth: "account",
    mutation: true,
    description: "Create a server.",
    docs: docs("servers-api"),
  },
  {
    name: "servers update",
    pattern: ["servers", "update", ":serverId"],
    method: "PUT",
    path: "/servers/:serverId",
    auth: "account",
    mutation: true,
    description: "Edit a server.",
    docs: docs("servers-api"),
  },
  {
    name: "servers delete",
    pattern: ["servers", "delete", ":serverId"],
    method: "DELETE",
    path: "/servers/:serverId",
    auth: "account",
    mutation: true,
    description: "Delete a server.",
    docs: docs("servers-api"),
  },
  {
    name: "streams list",
    pattern: ["streams", "list"],
    method: "GET",
    path: "/message-streams",
    auth: "server",
    description: "List message streams.",
    docs: docs("message-streams-api"),
  },
  {
    name: "streams get",
    pattern: ["streams", "get", ":streamId"],
    method: "GET",
    path: "/message-streams/:streamId",
    auth: "server",
    description: "Get a message stream.",
    docs: docs("message-streams-api"),
  },
  {
    name: "streams create",
    pattern: ["streams", "create"],
    method: "POST",
    path: "/message-streams",
    auth: "server",
    mutation: true,
    description: "Create a message stream.",
    docs: docs("message-streams-api"),
  },
  {
    name: "streams update",
    pattern: ["streams", "update", ":streamId"],
    method: "PUT",
    path: "/message-streams/:streamId",
    auth: "server",
    mutation: true,
    description: "Edit a message stream.",
    docs: docs("message-streams-api"),
  },
  {
    name: "streams archive",
    pattern: ["streams", "archive", ":streamId"],
    method: "POST",
    path: "/message-streams/:streamId/archive",
    auth: "server",
    mutation: true,
    description: "Archive a message stream.",
    docs: docs("message-streams-api"),
  },
  {
    name: "streams unarchive",
    pattern: ["streams", "unarchive", ":streamId"],
    method: "POST",
    path: "/message-streams/:streamId/unarchive",
    auth: "server",
    mutation: true,
    description: "Unarchive a message stream.",
    docs: docs("message-streams-api"),
  },
  {
    name: "messages outbound search",
    pattern: ["messages", "outbound", "search"],
    method: "GET",
    path: "/messages/outbound",
    auth: "server",
    description: "Search outbound messages.",
    docs: docs("messages-api"),
  },
  {
    name: "messages outbound details",
    pattern: ["messages", "outbound", "details", ":messageId"],
    method: "GET",
    path: "/messages/outbound/:messageId/details",
    auth: "server",
    description: "Get outbound message details.",
    docs: docs("messages-api"),
  },
  {
    name: "messages outbound dump",
    pattern: ["messages", "outbound", "dump", ":messageId"],
    method: "GET",
    path: "/messages/outbound/:messageId/dump",
    auth: "server",
    description: "Get outbound message dump.",
    docs: docs("messages-api"),
  },
  {
    name: "messages inbound search",
    pattern: ["messages", "inbound", "search"],
    method: "GET",
    path: "/messages/inbound",
    auth: "server",
    description: "Search inbound messages.",
    docs: docs("messages-api"),
  },
  {
    name: "messages inbound details",
    pattern: ["messages", "inbound", "details", ":messageId"],
    method: "GET",
    path: "/messages/inbound/:messageId/details",
    auth: "server",
    description: "Get inbound message details.",
    docs: docs("messages-api"),
  },
  {
    name: "messages inbound bypass",
    pattern: ["messages", "inbound", "bypass", ":messageId"],
    method: "PUT",
    path: "/messages/inbound/:messageId/bypass",
    auth: "server",
    mutation: true,
    description: "Bypass rules for a blocked inbound message.",
    docs: docs("messages-api"),
  },
  {
    name: "messages inbound retry",
    pattern: ["messages", "inbound", "retry", ":messageId"],
    method: "PUT",
    path: "/messages/inbound/:messageId/retry",
    auth: "server",
    mutation: true,
    description: "Retry a failed inbound message for processing.",
    docs: docs("messages-api"),
  },
  {
    name: "messages opens search",
    pattern: ["messages", "opens", "search"],
    method: "GET",
    path: "/messages/outbound/opens",
    auth: "server",
    description: "Search message opens.",
    docs: docs("messages-api"),
  },
  {
    name: "messages opens get",
    pattern: ["messages", "opens", "get", ":messageId"],
    method: "GET",
    path: "/messages/outbound/opens/:messageId",
    auth: "server",
    description: "Get opens for a single message.",
    docs: docs("messages-api"),
  },
  {
    name: "messages clicks search",
    pattern: ["messages", "clicks", "search"],
    method: "GET",
    path: "/messages/outbound/clicks",
    auth: "server",
    description: "Search message clicks.",
    docs: docs("messages-api"),
  },
  {
    name: "messages clicks get",
    pattern: ["messages", "clicks", "get", ":messageId"],
    method: "GET",
    path: "/messages/outbound/clicks/:messageId",
    auth: "server",
    description: "Get clicks for a single message.",
    docs: docs("messages-api"),
  },
  {
    name: "domains list",
    pattern: ["domains", "list"],
    method: "GET",
    path: "/domains",
    auth: "account",
    description: "List domains.",
    docs: docs("domains-api"),
  },
  {
    name: "domains get",
    pattern: ["domains", "get", ":domainId"],
    method: "GET",
    path: "/domains/:domainId",
    auth: "account",
    description: "Get a domain's details.",
    docs: docs("domains-api"),
  },
  {
    name: "domains create",
    pattern: ["domains", "create"],
    method: "POST",
    path: "/domains",
    auth: "account",
    mutation: true,
    description: "Create a domain.",
    docs: docs("domains-api"),
  },
  {
    name: "domains update",
    pattern: ["domains", "update", ":domainId"],
    method: "PUT",
    path: "/domains/:domainId",
    auth: "account",
    mutation: true,
    description: "Edit a domain.",
    docs: docs("domains-api"),
  },
  {
    name: "domains delete",
    pattern: ["domains", "delete", ":domainId"],
    method: "DELETE",
    path: "/domains/:domainId",
    auth: "account",
    mutation: true,
    description: "Delete a domain.",
    docs: docs("domains-api"),
  },
  {
    name: "domains verify-dkim",
    pattern: ["domains", "verify-dkim", ":domainId"],
    method: "PUT",
    path: "/domains/:domainId/verifyDkim",
    auth: "account",
    mutation: true,
    description: "Verify DKIM status.",
    docs: docs("domains-api"),
  },
  {
    name: "domains verify-return-path",
    pattern: ["domains", "verify-return-path", ":domainId"],
    method: "PUT",
    path: "/domains/:domainId/verifyReturnPath",
    auth: "account",
    mutation: true,
    description: "Verify Return-Path status.",
    docs: docs("domains-api"),
  },
  {
    name: "domains verify-spf",
    pattern: ["domains", "verify-spf", ":domainId"],
    method: "PUT",
    path: "/domains/:domainId/verifyspf",
    auth: "account",
    mutation: true,
    description: "Verify an SPF record.",
    docs: docs("domains-api"),
  },
  {
    name: "domains rotate-dkim",
    pattern: ["domains", "rotate-dkim", ":domainId"],
    method: "PUT",
    path: "/domains/:domainId/rotatedkim",
    auth: "account",
    mutation: true,
    description: "Rotate DKIM keys.",
    docs: docs("domains-api"),
  },
  {
    name: "signatures list",
    pattern: ["signatures", "list"],
    method: "GET",
    path: "/senders",
    auth: "account",
    description: "List sender signatures.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures get",
    pattern: ["signatures", "get", ":signatureId"],
    method: "GET",
    path: "/senders/:signatureId",
    auth: "account",
    description: "Get a sender signature's details.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures create",
    pattern: ["signatures", "create"],
    method: "POST",
    path: "/senders",
    auth: "account",
    mutation: true,
    description: "Create a sender signature.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures update",
    pattern: ["signatures", "update", ":signatureId"],
    method: "PUT",
    path: "/senders/:signatureId",
    auth: "account",
    mutation: true,
    description: "Edit a sender signature.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures delete",
    pattern: ["signatures", "delete", ":signatureId"],
    method: "DELETE",
    path: "/senders/:signatureId",
    auth: "account",
    mutation: true,
    description: "Delete a sender signature.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures resend-confirmation",
    pattern: ["signatures", "resend-confirmation", ":signatureId"],
    method: "POST",
    path: "/senders/:signatureId/resend",
    auth: "account",
    mutation: true,
    description: "Resend a sender signature confirmation.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures verify-spf",
    pattern: ["signatures", "verify-spf", ":signatureId"],
    method: "PUT",
    path: "/senders/:signatureId/verifyspf",
    auth: "account",
    mutation: true,
    description: "Verify sender signature SPF.",
    docs: docs("signatures-api"),
  },
  {
    name: "signatures request-new-dkim",
    pattern: ["signatures", "request-new-dkim", ":signatureId"],
    method: "POST",
    path: "/senders/:signatureId/requestnewdkim",
    auth: "account",
    mutation: true,
    description: "Request a new DKIM for a sender signature.",
    docs: docs("signatures-api"),
  },
  {
    name: "stats outbound overview",
    pattern: ["stats", "outbound", "overview"],
    method: "GET",
    path: "/stats/outbound",
    auth: "server",
    description: "Get outbound overview.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound sends",
    pattern: ["stats", "outbound", "sends"],
    method: "GET",
    path: "/stats/outbound/sends",
    auth: "server",
    description: "Get sent counts.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound bounces",
    pattern: ["stats", "outbound", "bounces"],
    method: "GET",
    path: "/stats/outbound/bounces",
    auth: "server",
    description: "Get bounce counts.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound spam",
    pattern: ["stats", "outbound", "spam"],
    method: "GET",
    path: "/stats/outbound/spam",
    auth: "server",
    description: "Get spam complaints.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound tracked",
    pattern: ["stats", "outbound", "tracked"],
    method: "GET",
    path: "/stats/outbound/tracked",
    auth: "server",
    description: "Get tracked email counts.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound opens",
    pattern: ["stats", "outbound", "opens"],
    method: "GET",
    path: "/stats/outbound/opens",
    auth: "server",
    description: "Get email open counts.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound open-platforms",
    pattern: ["stats", "outbound", "open-platforms"],
    method: "GET",
    path: "/stats/outbound/opens/platforms",
    auth: "server",
    description: "Get email platform usage.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound open-clients",
    pattern: ["stats", "outbound", "open-clients"],
    method: "GET",
    path: "/stats/outbound/opens/emailclients",
    auth: "server",
    description: "Get email client usage.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound clicks",
    pattern: ["stats", "outbound", "clicks"],
    method: "GET",
    path: "/stats/outbound/clicks",
    auth: "server",
    description: "Get click counts.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound click-browser-families",
    pattern: ["stats", "outbound", "click-browser-families"],
    method: "GET",
    path: "/stats/outbound/clicks/browserfamilies",
    auth: "server",
    description: "Get browser usage.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound click-platforms",
    pattern: ["stats", "outbound", "click-platforms"],
    method: "GET",
    path: "/stats/outbound/clicks/platforms",
    auth: "server",
    description: "Get browser platform usage.",
    docs: docs("stats-api"),
  },
  {
    name: "stats outbound click-location",
    pattern: ["stats", "outbound", "click-location"],
    method: "GET",
    path: "/stats/outbound/clicks/location",
    auth: "server",
    description: "Get click location.",
    docs: docs("stats-api"),
  },
  {
    name: "inbound-rules list",
    pattern: ["inbound-rules", "list"],
    method: "GET",
    path: "/triggers/inboundrules",
    auth: "server",
    description: "List inbound rule triggers.",
    docs: docs("inbound-rules-triggers-api"),
  },
  {
    name: "inbound-rules create",
    pattern: ["inbound-rules", "create"],
    method: "POST",
    path: "/triggers/inboundrules",
    auth: "server",
    mutation: true,
    description: "Create an inbound rule trigger.",
    docs: docs("inbound-rules-triggers-api"),
  },
  {
    name: "inbound-rules delete",
    pattern: ["inbound-rules", "delete", ":triggerId"],
    method: "DELETE",
    path: "/triggers/inboundrules/:triggerId",
    auth: "server",
    mutation: true,
    description: "Delete an inbound rule trigger.",
    docs: docs("inbound-rules-triggers-api"),
  },
  {
    name: "webhooks list",
    pattern: ["webhooks", "list"],
    method: "GET",
    path: "/webhooks",
    auth: "server",
    description: "List webhooks.",
    docs: docs("webhooks-api"),
  },
  {
    name: "webhooks get",
    pattern: ["webhooks", "get", ":webhookId"],
    method: "GET",
    path: "/webhooks/:webhookId",
    auth: "server",
    description: "Get a webhook.",
    docs: docs("webhooks-api"),
  },
  {
    name: "webhooks create",
    pattern: ["webhooks", "create"],
    method: "POST",
    path: "/webhooks",
    auth: "server",
    mutation: true,
    description: "Create a webhook.",
    docs: docs("webhooks-api"),
  },
  {
    name: "webhooks update",
    pattern: ["webhooks", "update", ":webhookId"],
    method: "PUT",
    path: "/webhooks/:webhookId",
    auth: "server",
    mutation: true,
    description: "Edit a webhook.",
    docs: docs("webhooks-api"),
  },
  {
    name: "webhooks delete",
    pattern: ["webhooks", "delete", ":webhookId"],
    method: "DELETE",
    path: "/webhooks/:webhookId",
    auth: "server",
    mutation: true,
    description: "Delete a webhook.",
    docs: docs("webhooks-api"),
  },
  {
    name: "suppressions dump",
    pattern: ["suppressions", "dump"],
    method: "GET",
    path: "/message-streams/:streamId/suppressions/dump",
    auth: "server",
    description: "Dump suppressions for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "suppressions dump",
    pattern: ["suppressions", "dump", ":streamId"],
    method: "GET",
    path: "/message-streams/:streamId/suppressions/dump",
    auth: "server",
    description: "Dump suppressions for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "suppressions create",
    pattern: ["suppressions", "create"],
    method: "POST",
    path: "/message-streams/:streamId/suppressions",
    auth: "server",
    mutation: true,
    description: "Create a suppression for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "suppressions create",
    pattern: ["suppressions", "create", ":streamId"],
    method: "POST",
    path: "/message-streams/:streamId/suppressions",
    auth: "server",
    mutation: true,
    description: "Create a suppression for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "suppressions delete",
    pattern: ["suppressions", "delete"],
    method: "POST",
    path: "/message-streams/:streamId/suppressions/delete",
    auth: "server",
    mutation: true,
    description: "Delete a suppression for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "suppressions delete",
    pattern: ["suppressions", "delete", ":streamId"],
    method: "POST",
    path: "/message-streams/:streamId/suppressions/delete",
    auth: "server",
    mutation: true,
    description: "Delete a suppression for a message stream.",
    docs: docs("suppressions-api"),
  },
  {
    name: "data-removals create",
    pattern: ["data-removals", "create"],
    method: "POST",
    path: "/data-removals",
    auth: "account",
    mutation: true,
    description: "Create a Data Removal request.",
    docs: docs("data-removals-api"),
  },
  {
    name: "data-removals get",
    pattern: ["data-removals", "get", ":requestId"],
    method: "GET",
    path: "/data-removals/:requestId",
    auth: "account",
    description: "Check a Data Removal request status.",
    docs: docs("data-removals-api"),
  },
];

export function findEndpoint(parts: readonly string[]): { endpoint: Endpoint; params: Record<string, string> } | undefined {
  for (const endpoint of endpoints) {
    const result = matchPattern(endpoint.pattern, parts);
    if (result) {
      return { endpoint, params: result };
    }
  }

  return undefined;
}

function matchPattern(pattern: readonly string[], parts: readonly string[]): Record<string, string> | undefined {
  if (pattern.length !== parts.length) {
    return undefined;
  }

  const params: Record<string, string> = {};

  for (let index = 0; index < pattern.length; index += 1) {
    const expected = pattern[index];
    const actual = parts[index];

    if (!expected || !actual) {
      return undefined;
    }

    if (expected.startsWith(":")) {
      params[expected.slice(1)] = actual;
      continue;
    }

    if (expected !== actual) {
      return undefined;
    }
  }

  return params;
}
